version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: logicqp-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    command: postgres -c log_statement=all

  postgrest:
    image: postgrest/postgrest:v12.0.2
    container_name: logicqp-postgrest
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
    ports:
      - "54321:3000"
    depends_on:
      - postgres

  kong:
    image: kong:2.8.1
    container_name: logicqp-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
    ports:
      - "8000:8000"
    volumes:
      - ./kong.yml:/var/lib/kong/kong.yml
    depends_on:
      - postgrest

volumes:
  postgres_data:

